services:
  servidor:
    build:
      context: ./servidor
      dockerfile: Dockerfile
    container_name: servidor_tflite
    ports:
      - "5001:5001"
    networks:
      - red_deteccion

  cliente:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    container_name: cliente_tflite
    depends_on:
      - servidor
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/video0:/dev/video0
    devices:
      - /dev/video0:/dev/video0
    networks:
      - red_deteccion

networks:
  red_deteccion:
    driver: bridge
